### ISSUE TITLE
Inconsistency in AcqEngMetadata handling of axisPosition.

### ISSUE THREAD

**Issue by nicost** [micro-manager/AcqEngJ#55]
AcqEngMetadata.setAxisPosition(JSONObject tags, String axis, Object position) allows addition of either a String or an integer to the JSONObject metadat.  When retrieving these with AcqEngMetadata.getAxisPosition(JSONObject tags, String axis), only an integer value is allowed, i.e. a String will throw a JSONException.  

This currently causes the acquisition with multiple channels to fail in Micro-Manager.  

Would it make more sense to have two functions, one to get the axisposition by index, the other to get the axisposition by name?  How do I force the acquisition engine to insert the channel index rather than channel name?

**Comment by henrypinkard** [comment]
> When retrieving these with AcqEngMetadata.getAxisPosition(JSONObject tags, String axis), only an integer value is allowed, i.e. a String will throw a JSONException.

Im not sure I understand. The `axis` should always be a `String` because it is e.g. (`"channel"`, `"z"`, etc.). The returned value, the position along the axis is what can be a `String` or `int`

**Comment by nicost** [comment]
Problem is that when it is a String,  `AcqEngMetadata.getAxisPosition(JSONObject tags, String axis)` will throw a JSONException.  I have no agency to set it to an int (would not even know where to do that).  It also seems very inconsistent that it is possible to set a String, but not to get it out.

**Comment by henrypinkard** [comment]
Does this solve the problem? https://github.com/micro-manager/AcqEngJ/pull/58



> Other issue is that all other axes are set by index, so why not this one?

Its nice to have the flexibility to use either String or integer keys to the axes. Some data is more logically consistent with positive integers, like a time series with distinct time points. But others that have no actual numeric relationship are better described by strings. For example, when you read data, if you want the FITC channel, its easier to identify it by its name rather than an arbitrary index which may change depending on what other channels are in the dataset. 

The acquisition engine allows any axis to be indexed by strings or integers (this is new though so there may still be bugs, like the one you just found). 

So any of the following are valid axes:

```python
{"time": 1, "channel": "DAPI"}
{"time": "first", "channel": 0}
{"time": "first", "channel": "DAPI"}
```

The only constraint is that you cant mix string and integer positions along a single axis

I just added this ability to use either ints or string and the adapter code predates it and was using the old (admittedly arbitrary) mechanism where channels were strings and everything else was ints

**Comment by nicost** [comment]
Got it to work by changing the code in org.micromanager.acquisition.internal.acqengjcompat.MDAAcqEventModules line 120 from:

`channelEvent.setChannelName(channelList.get(index).config());`
to 
`channelEvent.setAxisPosition(AcqEngMetadata.CHANNEL_AXIS, index);`

I think your change is sound.  There is still a lot I do not understand...

**Comment by henrypinkard** [comment]
Yes that looks right!
